openapi: 3.0.4
info:
  title: MCP API with OAS extensions
  version: 1.0.26
  x-mcp-instructions: |-
    Do NOT use HelloWorldNew tool, it is not ready for production.
    To greet a user, first ask their age. If they are minor, decline politely.
servers:
  - url: /api
paths:
  /greet/old:
    get:
      x-mcp-tool-name: GreetOld_FromExtension
      operationId: GreetOld_FromOperationId #x-mcp-tool-name should be used instead
      description: From get /greet/old operation description
      parameters:
        - name: age
          in: query
          schema:
            type: number
      responses:
        "200":
          description: Successful operation
  /greet/new:
    get:
      operationId: GreetNew_FromOperationId
      x-mcp-tool-description: From get /greet/new extension description
      description: From get /greet/new operation description #x-mcp-tool-description should be used instead
      parameters:
        - name: age
          in: query
          schema:
            type: number
      responses:
        "200":
          description: Successful operation
  /greet:
    get:
      x-mcp-tool-enabled: false
      parameters:
        - name: age
          in: query
          schema:
            type: number
      responses:
        "200":
          description: Successful operation
