openapi: 3.0.4
info:
  title: MCP API
  version: 1.0.26
servers:
  - url: /api
paths:
  /valid-tool-name/{test}:
    description: Some description
    parameters:
      - name: test
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: validOperationId
      responses:
        '200':
          description: Successful operation
    post:
      responses:
        '200':
          description: Successful operation
  /invalid-tool-name:
    get:
      operationId: SuperSuperSuperSuperLongOperationIdSoTheToolNameIsLongerThan64Chars
      responses:
        '200':
          description: Successful operation
    post:
      x-mcp-tool-name: "Invalid tool name from x-mcp-tool-name"
      operationId: Valid
      responses:
        '200':
          description: Successful operation
  /invalid-tool-name-because-the-path-is-way-to-long/{long-parameter}:
    post:
      parameters:
        - name: long-parameter
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation