name: .NET Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x # Adjust if your project uses a different .NET version
      - name: Restore dependencies
        run: dotnet restore OpenApiToMcp/OpenApiToMcp.csproj
      - name: Build
        run: dotnet build OpenApiToMcp/OpenApiToMcp.csproj --no-restore
