name: Create Release

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    name: Build and Publish CLI for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            artifact-name: openapi-to-mcp-win-x64
          - os: macos-latest
            rid: osx-arm64
            artifact-name: openapi-to-mcp-osx-arm64

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # Adjust if needed

      - name: Publish CLI
        run: dotnet publish OpenApiToMcp.Cli/OpenApiToMcp.Cli.csproj -c Release -r ${{ matrix.rid }} --self-contained true -p:EnableCompressionInSingleFile=true -o ./publish/${{ matrix.rid }}
        shell: bash

      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ./publish/${{ matrix.rid }}/OpenApiToMcp.Cli.exe

      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ./publish/${{ matrix.rid }}/OpenApiToMcp.Cli
